### ISSUE TITLE
Return Response after Verify

### ISSUE THREAD

**Issue by driverpt** [agorapulse/gru#67]
Currently we are using Spring WebTestClient and it allows us to return the Body itself for further dynamic assertions, e.g.:

```
List<SomeObject> result = webTestClient.post()
            .uri(url)
            .contentType(MediaType.APPLICATION_JSON)
            .accept(MediaType.APPLICATION_JSON)
            .body(Mono.just(body), SomeBodyClass.class)
            .exchange()
            .expectStatus().is2xxSuccessful()
            .expectBody(new ParameterizedTypeReference<List<SomeObject>>() {})
            .returnResult()
            .getResponseBody();

assertThat(result).hasSize(1);
```

Is it possible to do the same for Gru?

**Comment by musketyr** [comment]
At the moment, the assertions in Gru are done on different level. You are specifying the expected JSON (or other fixture files such as plain text or HTML). For JSON you can leverage JsonUnit marchers 

https://github.com/lukas-krecan/JsonUnit

Gru is highly extendible. You can access the request and response from your own `Minion` and do some other assertions.

https://agorapulse.github.io/gru/#_extending_gru

**Comment by musketyr** [comment]
done https://agorapulse.github.io/gru/#_capturing_text_response
