### ISSUE TITLE
[Bug] NPE if second verification is made

### ISSUE THREAD

**Issue by driverpt** [agorapulse/gru#68]
Hey folks,

We have detected a Bug in Gru. If we call `verify` twice, the `baseUri` is `null` on the second, meaning that Context is lost.

Test Case:

```
  @Test
  public void testGru() throws Throwable {
    // Call one endpoint
    httpClient
      .verify(test -> test
        .get("/actuator/health")
        .expect(response -> response
          .status(OK)));

    /* Do some more stuff here */

    // Call another Endpoint
    httpClient
      .verify(test -> test
        .get("/actuator/health")
        .expect(response -> response
          .status(OK)));
  }

```

If we Debug this, we notice that in the second invocation in `GruHttpRequest.buildOkHttpRequest()`, `baseUri` is null.

Update: we found the Root Cause. Spring's Autoconfigurer calls `.create(...).prepare(<baseUri>)` but after each `.verify()`, `.reset()` is called, which clears the `configurations` (including BaseUri).

Is it a good idea fo make `baseUri` an external parameter rather than a generic `configuration`?

**Comment by musketyr** [comment]
indeed. the original purpose to run verify once per test method. I will take a look if there is a way how reset the state without cleaning the base URL

**Comment by driverpt** [comment]
The easier way seems like a dedicated property for base uri.
