### ISSUE TITLE
Grails multipart command object not binding correctly

### ISSUE THREAD

**Issue by sbglasius** [agorapulse/gru#76]
I have added an example here https://github.com/agorapulse/gru/pull/77, where it shows, that data binding to command objects are not working correctly when using MultiPart in a command object. 
I'm not 100% sure, that this is a GRU problem, but I'm hoping that someone can help me identify it. If I make the same test as an integration test, it works (included in example app)

**Comment by musketyr** [comment]
Hello @sbglasius, thank you for reporting. I dig deeper and found out that the file parameter is missing in the `DataBindingSource` so I'm afraid this goes beyond Gru. `DefaultDataBindingSourceCreator#createDataBindingSource(java.lang.Object, javax.servlet.http.HttpServletRequest)` is using `GrailsWebRequest#getParams()` which does not contain the file parameter.  

You can still use [Gru with an integration test](https://agorapulse.github.io/gru/#_integration_tests).
