### ISSUE TITLE
How to get response headers?

### ISSUE THREAD

**Issue by akefirad** [agorapulse/gru#83]
I'm trying to read response headers to use for further assertions. But not sure how to do it. Looking at minions, it seems HttpMinion is the one to use:
```groovy
def headers = gru.squad.ask(HttpMinion) { 
  responseHeaders
}
```
But it's empty. I'm quite new to Gru so I might be missing something, but looking at HttpMinion code it doesn't seem to collect the response headers at all. The field is not used anywhere. What's the correct way to access response headers? Thanks.

**Comment by musketyr** [comment]
Hi, all the response values should be considered internal. If you need to verify headers then you should use

```
expect {
    header 'Name', 'Value'
}
```

**Comment by akefirad** [comment]
Right. But the use case is to read the value not to verify it.

**Comment by musketyr** [comment]
This is not supported. In theory, you should be able to apply call from your sample but it would have to be between call to `gru.test` and `gru.verify` (not using implicit `asBoolean` from `expect:` block nor the `verify` method.

```
when:
    gru.test { ... }
    def headers = gru.squad.ask(HttpMinion) { 
      responseHeaders
    }
    
then:
    gru.verify()
```

**Comment by musketyr** [comment]
oh, sorry for confusion. I believe the `responseHeaders` are the ones which are supposed to be asserted not the one from the response.

**Comment by musketyr** [comment]
also well spotted for the `responseHeaders` - they are really unused at the moment, replaced by `responseHeadersMatchers`

**Comment by akefirad** [comment]
Right. Well this is a bit sub-optimal. In my use case I've got an ID that comes back in the response and I'd like to do further verification against the database (to make sure the server is sending the right ID). And since it's kinda random I don't know in advance its value. So I have to collect it from the header and use it further down the line to check the data in the database. Currently I hacked it by create a special matcher call CapturingMatcher which essentially does capture-if-matched and then use it later. (It like the hack of using a single-cell array to capture data from a lambda in Java, just a bit prettier 😄).

**Comment by akefirad** [comment]
> Indeed, adding the ID into header is a kind of hack itself
Well, I wouldn't make sure a generic statement 🙂.
> the ID is somewhere in the body?
No, the ID is not part the response body. It's more about the communication it self. It's not exactly like Request-Id but for the sake of discussion we can assume it's the request ID.

**Comment by musketyr** [comment]
see https://agorapulse.github.io/gru/#_capturing_text_response
